### ISSUE TITLE
Cannot switch to settings from the view of a problem

### ISSUE THREAD

**Issue by Benezivas** [Benezivas/algobattle-web#15]
When selecting the detail view of any problem and subsequently selecting the settings, the link is not followed. Instead, `settings` replaces the problem name in the url, resulting in a faulty link.

Example: 
`https://www.algobattle.org/problems/WS23%2F24/Pairsum` becomes
`https://www.algobattle.org/problems/WS23%2F24/settings`

**Comment by ImogenBits** [comment]
fixed in next release
