### ISSUE TITLE
Uploading a report fails

### ISSUE THREAD

**Issue by Benezivas** [Benezivas/algobattle-web#2]
The teams of our lab course reported that they were unable to use the upload function that is accessible in the description of a given problem. They were able to open the file upload dialogue, but subsequently selecting the `Upload` button did not result in any response from the system.

We are able to reproduce this error with our `LuFGTI` team on `algobattle.org`. This seems curious, as this did work before.

**Comment by ImogenBits** [comment]
fix in dev build, will push release to server later today.
