### ISSUE TITLE
Inactive problem still selectable in upload dialog

### ISSUE THREAD

**Issue by Glirastes** [Benezivas/algobattle-web#6]
In the upload dialog for generators or solvers, problems currently inactive (Pairsum, 2D Knapsack) are still selectable. However, when attempting to actually upload a program for such a problem, the upload is denied (as probably intended). I'd suggest to make inactive problems not selectable at least, maybe even remove them from the list completely.  
  
![U_000034](https://github.com/Benezivas/algobattle-web/assets/91015021/7ba397fe-9891-4110-8263-c64cfd303c50)

**Comment by ImogenBits** [comment]
In the next release the dropdown will only include currently active problems (i.e. ones that you can actually upload programs for). Additionally, if there is only a single active problem it will be preselected already.
