### ISSUE TITLE
Pre-fill "Edit Result" mask with data of the corresponding result

### ISSUE THREAD

**Issue by Benezivas** [Benezivas/algobattle-web#7]
When editing an existing result, e.g. in order to remove a team from a battle that did not participate or in order to edit points, one has to to manually select for each team which generator and solver should be associated with the result.

The date field is also behaving unintuitively: The result is saved with a starting date that is precise up to a second, but non-zero seconds may not be saved.

It would be nice if the editing mask would be filled with the required data such that single changes can be made without having to select and edit multiple other fields before being able to save.

**Comment by ImogenBits** [comment]
This actually is a bug, it was meant to behave like that already. Is fixed in the current version.
