### ISSUE TITLE
Adding result by hand fails

### ISSUE THREAD

**Issue by Benezivas** [Benezivas/algobattle-web#9]
I am trying to add a new result for a  problem by hand:

I have created a dummy problem for bug bounties, which is dated in the past. I am now trying to add a result using the "Add result" mask on the corresponding page. Selecting this dummy problem, adding one team, selecting "None" for solvers and generators, dating the problem in the past and then trying to send off this data does not work: Clicking the corresponding button has no effect.

The backend reports "422 Unprocessable Entity", but gives no further information.
Some more detail on the data entered for reproducibility:
Date: 2023-10-31 00:01 AM
Problem: Bug Bounty
Status: Complete
Log File: None Selected
One team added, "Team Tiger" with "None" selected for Solver and Generator, 70 points selected

**Comment by ImogenBits** [comment]
fixed in next release
